[tool.poetry]
name = "pyproject-toml"
version = "1"
description = "1"
authors = ["1"]
readme = "README.md"
packages = [{include = "pyproject"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
